language: go
os: linux
dist: xenial
go:
  - 1.16.3

script:
  - make test
  - make build

deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  token: $GITHUB_TOKEN
  file: dist/gojira
  skip_cleanup: true
  on:
    tags: true