language: go

go:
  - 1.16.3

script:
  - make test
  - make build

deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  api_key: $GITHUB_TOKEN
  file: dist/gojira
  skip_cleanup: true
  on:
    tags: true